### PR TITLE
Adding AutOntology tool

### PR DESCRIPTION
**Pull request by meganpowers1**

### CODE REVIEW

**Comment by rmcgranaghan** [comment]
@meganpowers1 this is excellent! Thanks for preparing. My comments for you to consider: 

- It might be helpful to have a list of dependencies for the tool. Perhaps something like a yml file or other means of automatically installing those dependencies
- It would be helpful to further describe the format of the training data that is required. This is an important aspect of the usefulness of the resultant ontology and likely an area where other contributors/users will modify, so outlining the process of providing a new training corpus is important. 
- How might general language models be used to augment this? Can you offer sample code that perhaps begins with general language models and uses the Helio-specific data to augment and then output the ontology based on the combination?

**Comment by rmcgranaghan** [comment]
@meganpowers1 this is excellent! Thanks for preparing. My comments for you to consider: 

- It might be helpful to have a list of dependencies for the tool. Perhaps something like a yml file or other means of automatically installing those dependencies
- It would be helpful to further describe the format of the training data that is required. This is an important aspect of the usefulness of the resultant ontology and likely an area where other contributors/users will modify, so outlining the process of providing a new training corpus is important. 
- How might general language models be used to augment this? Can you offer sample code that perhaps begins with general language models and uses the Helio-specific data to augment and then output the ontology based on the combination?

**Comment by rmcgranaghan** [comment]
@meganpowers1 friendly check-in on the status of the updates I mentioned?

**Comment by meganpowers1** [comment]
I have addressed these comments in a new branch @rmcgranaghan

**Pull request merged**
